version: '2'
services:
  app:
    build:
      context: .
    ports:
      - 8009:8000
    volumes:
      - ./:/usr/src/app
    restart: always
    env_file: .env
networks:
  default:
    external:
      name: eddy